/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";
import { Mesh } from 'three'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/laptop.gltf')
  

  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.laptop_1.geometry} material={materials.aiStandardSurface7SG} />
        <mesh geometry={nodes.laptop_2.geometry} material={materials.aiStandardSurface4SG} />
        <mesh geometry={nodes.laptop_3.geometry} material={materials.initialShadingGroup} />
        <mesh geometry={nodes.laptop_4.geometry} material={materials.aiStandardSurface5SG} />
        <mesh geometry={nodes.laptop_5.geometry} material={materials.aiStandardSurface1SG} />
        <mesh geometry={nodes.laptop_6.geometry} material={materials.aiStandardSurface3SG} />
        <mesh geometry={nodes.laptop_7.geometry} material={materials.aiStandardSurface6SG} />
      </group>
      <mesh geometry={nodes.lista.geometry} material={materials.lista} position={[0.11, 2.25, -1.95]} rotation={[Math.PI / 2, 0, 0]} scale={[4.09, 4.01, 3.7]} />
    </group>
  )
}

useGLTF.preload('/laptop.gltf')
